config/routes.rb
Rails.application.routes.draw do
  get 'profiles/new'
  get 'profiles/index'
  get 'profiles/show'
  get 'profiles/edit'
  root 'services#index'

  devise_for :users,
    controllers: {
      sessions: 'devise/sessions',
      registrations: "users/registrations",
      omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :services do
    collection do
      match 'search' => 'services#search', via: [:get, :post]
    end
  end

  resources :profiles
  resources :favorites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div class="notification is-danger">
		<h2><%= pluralize(object.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
		<ul>
			<% object.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_like.html.erb
<div class="panel-block">
	<% if @service.user_id != current_user.id %>
	<% if @like.present? %>
	<%= link_to 'quit_like_list', like_path(id: @like.id), method: :delete, class: "button btn-like", style: "background-color:#ca4837; color:white; border: none;" %>
	<% else %>
	<%= link_to 'add_like_list', likes_path(service_id: @service.id), method: :post, class: "button btn-like", style: "background-color:#eed66d; color:black; border: none;" %>
	<% end %>
	<% end %>
</div>
<div class="panel-block">
	<p class="like-user">ウォッチャー：</p>
	<p class="like-user-name">
		<% @likes.each do |like| %>
		<%= like.name %>
		<% end %>
	</p>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.following.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>