config/routes.rb
Rails.application.routes.draw do
  get 'profiles/new'
  get 'profiles/index'
  get 'profiles/show'
  get 'profiles/edit'
  root 'services#index'

  devise_for :users,
    controllers: {
      sessions: 'devise/sessions',
      registrations: "users/registrations",
      omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :services do
    collection do
      match 'search' => 'services#search', via: [:get, :post]
    end
  end

  resources :profiles
  resources :favorites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="content has-text-centered">
			2020 ©dic_aokazu
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
	<nav class="navbar" role="navigation" aria-label="main navigation"></nav>
	<div class="navbar-brand">
		<div class="navbar-item">
			<%= link_to root_path, class: "navbar-item" do %>
			<h1 class="title is-3" style="font-family: cursive;">win-win!!!!!</h1>
			<% end %>
		</div>
	</div>

	<div class="navbar-item">
		<div class="nabvar-search">
			<%= search_form_for @search, url: services_path do |f| %>
			<%= f.label :Main_Keyword %>
			<%= f.text_field :main_service_id_cont, placeholder: '何をお探しですか？' %>
			<%= f.label :Sub_Keyword %>
			<%= f.text_field :service_detail_id_cont, placeholder: '何をお探しですか？' %>
			<%= f.select( :sorts, { '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc',
	                                      '出品の新しい順': 'updated_at desc' }, { onchange: 'this.form.submit()'} ) %>
			<%= f.submit class: 'btn-search' %>
			<% end %>
		</div>
	</div>

	<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
		data-target="navbarBasicExample">
		<span aria-hidden="true"></span>
		<span aria-hidden="true"></span>
		<span aria-hidden="true"></span>
	</a>

	<% if user_signed_in? %>
	<div id="navbarBasicExample" class="navbar-menu">
		<div class="navbar-start">
			<div class="navbar-item">
				<%= link_to "サービス投稿", new_service_path, method: :get, class: "button is-info is-rounded" %>
			</div>

			<div class="navbar-item">
				<%= link_to "マイページ", user_path(current_user), class: "button is-info is-rounded" %>
			</div>
		</div>

		<div class="navbar-end">
			<div class="navbar-item">
				<%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-info is-rounded" %>
			</div>
		</div>
	</div>

	<% else %>
	<div id="navbarBasicExample" class="navbar-menu">
		<div class="navbar-item">
			<%= link_to "ログイン", new_user_session_path, class: "button is-info is-rounded" %>
		</div>

		<div class="navbar-item">
			<%= link_to "新規登録", new_user_registration_path, class: "button is-info is-rounded" %>
		</div>
	</div>
	<% end %>
	</nav>
</header>

app/views/layouts/_main_body.html.erb
<div class="submenu column is-2">
	<p class="greeting">ようこそ!!</p>
	<div class="current-user-name">
		<% if user_signed_in? %>
		<%= current_user.name %>
		<% else %>
		<%= current_user %>
		<% end %>
	</div>

	<aside class="box menu">
		<!-- <p class="menu-label">
			【（仮）おすすめ情報 】
		</p>
		<ul class="menu-list">
			<li><a href="#">売れ筋情報<small>@uresugi</small></a></li>
			<li><a href="#">喜びの声<small>@voice</small></a></li>
			<li><a href="#">おすすめ<small>@recommendation</small></a></li>
		</ul> -->

		<% if user_signed_in? %>
		<p class="menu-label">
			【 LINK 】
		</p>
		<ul class="menu-list">
			<li>
				<%= link_to "services", services_path, class: "button is-warning" %>
			</li>

			<ul>
				<li>
					<%= link_to "users", users_path  %>
				</li>

				<li>
					<%= link_to "profiles", profiles_path  %>
				</li>
			</ul>

			<li>
				<%= link_to "Create Profile", new_profile_path(current_user), class: "button is-info" %>
			</li>
		</ul>
	</aside>
	<% end %>
</div>

<div class="column">
	<service class="box media">
		<div class="media-content">
			<%= yield %>
			<%= javascript_pack_tag "application" %>
		</div>
	</service>
</div>

app/views/layouts/_main_title.html.erb
<div class="hero is-info is-bold">
	<div class="hero-body">
		<div class="container">
			<h2 class="subtitle-ja">あなたのスキルで誰かが喜ぶ。 そして、あなたはやりがいを得る。 それがこのアプリ「win-win!!!!!」です。</h2>
			<h4 class="subtitle-en">Someone will love your skills. And you get rewarded. That's this app "win-win!!!!!".
			</h4>
		</div>
	</div>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all'%>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta charset="utf-8">
<script src="https://kit.fontawesome.com/c135f5a922.js" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script async defer crossorigin="anonymous"
	src="https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v7.0&appId=696006411132834&autoLogAppEvents=1"
	nonce="7u1eXOwL">
	</script>
<script type="text/javascript">
	document.querySelector('.navbar-burger').addEventListener("click", toggleNav);

	function toggleNav() {
		var nav = document.querySelector('.navbar-menu');
		if (nav.className == "navbar-menu") {
			nav.className = "navbar-menu is-active";
		} else {
			nav.className = "navbar-menu";
		}
	}
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WinWin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>